# Generated by Django 5.1.1 on 2024-10-01 15:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(default='bg.jpg', upload_to='event_photos/'),
        ),
        migrations.AddField(
            model_name='match',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='match_photos/'),
            preserve_default=False,
        ),
    ]
