# Generated by Django 5.1.1 on 2024-10-02 09:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_event_photo_match_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='opponent',
            new_name='away_team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='photo',
        ),
        migrations.AddField(
            model_name='match',
            name='away_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team_logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/'),
        ),
        migrations.AddField(
            model_name='match',
            name='league_logo',
            field=models.ImageField(blank=True, null=True, upload_to='league_logos/'),
        ),
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
