# Generated by Django 5.1.1 on 2024-10-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_gallery_comment_like_reaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='GalleryItem',
        ),
    ]
